# Generated by Django 3.1.4 on 2021-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0003_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
