# Generated by Django 3.1.4 on 2021-03-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0005_auto_20210217_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Examination instruments', 'Examination instruments'), ('Retractor', 'Retractor'), ('Local anesthesia', 'Local anesthesia'), ('Dental hand piece', 'Dental hand piece'), ('Dental laser', 'Dental laser'), ('Dental torque wrench', 'Dental torque wrench'), ('Burs', 'Burs'), ('Restorative instruments', 'Restorative instruments'), ('Burnishers', 'Burnishers'), ('Pluggers', 'Pluggers'), ('Periodontal', 'Periodontal'), ('Prosthodontic instruments', 'Prosthodontic instruments'), ('Extraction and surgical instruments', 'Extraction and surgical instruments'), ('Orthodontic instruments', 'Orthodontic instruments'), ('Endodontic instruments', 'Endodontic instruments'), ('Furniture', 'Furniture')], max_length=50, null=True),
        ),
    ]
